"""add SignatureImage model

Revision ID: 1bb5bd2a5c04
Revises: a797fd071986
Create Date: 2026-02-07 19:38:37.001440

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1bb5bd2a5c04"
down_revision = "a797fd071986"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signature_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("image_path", sa.String(length=255), nullable=False),
        sa.Column("filename", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("signature_images")
    # ### end Alembic commands ###
