"""add_ai_raw_responses_table

Revision ID: 20260213_001
Revises: 422c5ca23883
Create Date: 2026-02-13 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260213_001'
down_revision = '422c5ca23883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_raw_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=False),
    sa.Column('ki_model', sa.String(length=100), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('processing_status', sa.String(length=20), nullable=True),
    sa.Column('observation_area', sa.String(length=100), nullable=True),
    sa.Column('context_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_raw_responses')
    # ### end Alembic commands ###
