"""add_content_edits_table

Revision ID: 20260213_002
Revises: 20260213_001
Create Date: 2026-02-13 15:00:01.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260213_002'
down_revision = '20260213_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_edits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_response_id', sa.Integer(), nullable=False),
    sa.Column('version_type', sa.String(length=50), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('diff_metrics', sa.JSON(), nullable=False),
    sa.Column('edit_reason', sa.Text(), nullable=True),
    sa.Column('edited_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['edited_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['raw_response_id'], ['ai_raw_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_edits')
    # ### end Alembic commands ###
