"""add_learned_prompt_rules_table

Revision ID: 20260213_003
Revises: 20260213_002
Create Date: 2026-02-13 15:00:02.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260213_003'
down_revision = '20260213_002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learned_prompt_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('observation_area', sa.String(length=100), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('rule_content', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('samples_analyzed', sa.Integer(), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('applied_in_prompt_version', sa.Integer(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learned_prompt_rules')
    # ### end Alembic commands ###
