"""Add ExplanationBlock model

Revision ID: 37910f5c8ff0
Revises: ffbd6aad0758
Create Date: 2026-02-06 12:03:05.714260

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "37910f5c8ff0"
down_revision = "ffbd6aad0758"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "explanation_blocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("explanation_blocks")
    # ### end Alembic commands ###
