"""add unique constraint to prompt name

Revision ID: 65898bde1230
Revises: 1bb5bd2a5c04
Create Date: 2026-02-08 14:13:24.407533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65898bde1230'
down_revision = '1bb5bd2a5c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_prompts_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_prompts_name', type_='unique')

    # ### end Alembic commands ###
