"""Add report system tables: ReportTemplate, ReportConfiguration, CompanyLogo, ClientLogo

Revision ID: a797fd071986
Revises: b4c7ad2a2bbc
Create Date: 2026-02-07 17:05:31.243174

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a797fd071986"
down_revision = "b4c7ad2a2bbc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_logos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("logo_path", sa.String(length=255), nullable=False),
        sa.Column("filename", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "report_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("design_config", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "client_logos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("logo_path", sa.String(length=255), nullable=False),
        sa.Column("filename", sa.String(length=100), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "report_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.Column("company_logo_id", sa.Integer(), nullable=True),
        sa.Column("client_logo_id", sa.Integer(), nullable=True),
        sa.Column("modules_config", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_logo_id"],
            ["client_logos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_logo_id"],
            ["company_logos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["report_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("report_configurations")
    op.drop_table("client_logos")
    op.drop_table("report_templates")
    op.drop_table("company_logos")
    # ### end Alembic commands ###
