"""Initial migration with all models

Revision ID: ffbd6aad0758
Revises:
Create Date: 2025-10-04 13:25:38.188424

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ffbd6aad0758"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column("leitung_fremdeinschatzung", sa.String(length=100), nullable=True),
        sa.Column("beobachter1", sa.String(length=100), nullable=True),
        sa.Column("beobachter2", sa.String(length=100), nullable=True),
        sa.Column("leitung_selbsteinschatzung", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prompts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "participants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("general_data", sa.Text(), nullable=True),
        sa.Column("observations", sa.Text(), nullable=True),
        sa.Column("sk_ratings", sa.Text(), nullable=True),
        sa.Column("vk_ratings", sa.Text(), nullable=True),
        sa.Column("ki_texts", sa.Text(), nullable=True),
        sa.Column("ki_raw_response", sa.Text(), nullable=True),
        sa.Column("footer_data", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "self_assessments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("participant_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("participant_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("self_assessments")
    op.drop_table("participants")
    op.drop_table("prompts")
    op.drop_table("groups")
    # ### end Alembic commands ###
